jobs:
 - name: u14cppall-test
   type: runSh
   steps:
     - IN: u14all-testing
     - TASK:
         runtime:
           options:
             imageName: "drydock/u14cppall"
             imageTag: master
         script:
          - gcc --version
          - autoconf --version
          - automake --version
          - ccache --version
          - clang --version
